# Generated by Django 6.0.1 on 2026-01-28 15:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Содержимое'),
        ),
    ]
