# Generated by Django 6.0.1 on 2026-01-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='calculated_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Рассчитанная сумма'),
        ),
    ]
