# Generated by Django 6.0.1 on 2026-01-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('unisex', 'Унисекс'), ('male', 'Мужской'), ('female', 'Женский')], default='unisex', max_length=10, verbose_name='Пол'),
        ),
    ]
