# Generated by Django 6.0.1 on 2026-01-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('medical', 'Медицинская одежда'), ('horeca', 'HoReCa')], default='medical', max_length=10, verbose_name='Тип категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название подкатегории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('unisex', 'Унисекс'), ('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол (только для медицины)'),
        ),
    ]
