# Generated by Django 5.2.12 on 2026-03-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_type_remove_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название баннера')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение баннера')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Баннер главной',
                'verbose_name_plural': 'Баннеры главной',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('medical', 'Медицинская одежда'), ('horeca', 'HoReCa')], max_length=10, verbose_name='Тип категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
