# Generated by Django 5.2.12 on 2026-03-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_homepagebanner_category_type_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='catalog_banners/', verbose_name='Изображение баннера')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Баннер каталога',
                'verbose_name_plural': 'Баннеры каталога',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('unisex', 'Унисекс'), ('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол (только для медицины)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
